# Make sure the folder exists (ok if it already does)
mkdir .github\workflows -Force | Out-Null

# Overwrite ci.yml with a clean workflow
@'
name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ Workflow triggered and running."

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install project (editable) + dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run tests
        run: pytest -q
'@ | Set-Content .github\workflows\ci.yml -Encoding UTF8
